### PR TITLE
Rename properties "description"

### PR DESCRIPTION
**Pull request by tschmidtb51**
- resolves oasis-tcs/csaf#138
- rename "description" to "details" or "discussion"
- fix examples

### CODE REVIEW

**Review by sthagen — APPROVED** [review]
We may want to ask the members of the TC, if in some cases even `details` should give way to `summary` for being more adequate.

**Comment by santosomar** [comment]
We can send it via email before the next meeting.

**Review by santosomar — APPROVED** [review]

**Comment by mprpic** [comment]
This is more of a nitpick, but the word "discussion" to me implies opinions from multiple parties but in most cases a CSAF document will be produced by a single entity. A discussion where only one person speaks is more of a summary :-)

:+1: on the rest of the changes proposed here.

**Comment by sthagen** [comment]
@mprpic summary is a good resolution for me - I even lean on naming most of these summary, as details has very loose semantics - not clear if those are noise or contribution. What do you think?

**Comment by tschmidtb51** [comment]
> This is more of a nitpick, but the word "discussion" to me implies opinions from multiple parties but in most cases a CSAF document will be produced by a single entity. A discussion where only one person speaks is more of a summary :-)

I'm a little bit worried that if we use the word "summary" we will loose the details (as a summary usually skips the details and provides only an overview). IMHO this doesn't reflect the content we had in mind. For me, a "discussion" can also be done by one person if he/she takes all different aspects of the topic in to consideration and provides a chain of reasoning for the conclusion.

However, I also agree with @sthagen:
> details has very loose semantics

So I hope that the description of the field will provide enough guidance to the author to make it clear what and in which level of detail information should be provided.

**Comment by tschmidtb51** [comment]
There is one point where I would prefer "summary" over "details":
```/document/tracking/revision_history/[]/description```

We don't really need all the details (where did the author change a typo or which whitespace was added) but only the fact that typos were corrected (and there were no changes to the semantic / pragmatics).

**Comment by santosomar** [comment]
Let's discuss this one in the meeting tomorrow. Thank you for all your time and help on this folks!

**Comment by sthagen** [comment]
Discussed and resolved in meeting 2020-10-28 as documented in https://github.com/oasis-tcs/csaf/issues/138#issuecomment-718105908 - @tschmidtb51 volunteered to amend this PR then a maintainer (@santosomar or @sthagen) will merge. Thank you to the whole TC for the dicussion and effort to resolve the issue #138

**Pull request merged**
