### PR TITLE
Sanitizing HTML

### PR DESCRIPTION
**Pull request by tschmidtb51**
- addresses parts of oasis-tcs/csaf#174
- replace SHALL with SHOULD to allow for conforming CSAF producers
- add remark about Markdown's code options
- add remark about processing on CSAF consumer side
- add remark about additional safeguards

### CODE REVIEW

**Review by santosomar — APPROVED** [review]

**Review by sthagen — APPROVED** [review]
I think this is an important and welcome change to allow tools to process and present markup without becoming non-compliant. Thanks.

**Comment by tolim** [comment]
@tschmidtb51, thanks for the changes. I like it!

**Review by mprpic — APPROVED** [review]

**Comment by santosomar** [comment]
from Art MANION (Guest) to Everyone:    1:53  PM
to include HTML, source code, or any other content that may be interpreted or executed by a CSAF reader, use fence...

**Comment by santosomar** [comment]
This pull requests was discussed and approved during the June 30, 2021 CSAF TC Monthly meeting.

**Comment by tschmidtb51** [comment]
@santosomar: Ready for Merge.

**Review by sthagen — APPROVED** [review]
LGTM.

**Pull request merged**
