### PR TITLE
Guidance on CPE pattern (for CSAF 2.0)

### PR DESCRIPTION
**Pull request by tschmidtb51**
- addresses parts of oasis-tcs/csaf#693
- add FAQ regarding usage of the new pattern

### CODE REVIEW

**Review by sthagen — APPROVED** [review]
LGTM.

**Comment by santosomar** [comment]
During the 2024-05-29 CSAF TC monthly meeting we discussed that a motion will be send via email to approve the changes as suggested.

**Comment by santosomar** [comment]
The motion to accept the pull request as suggested in https://github.com/oasis-tcs/csaf/pull/740 and include it into the guidance towards CSAF 2.0, has passed. It automatically carried on 2024-06-05 23:00 UTC.
https://groups.oasis-open.org/discussion/motion-for-740

**Review by santosomar — APPROVED** [review]
Thank you for all your contributions @tschmidtb51 !

**Pull request merged**
