### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by wurstbrot**

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@mprpic Could you please double-check?

**Comment by tschmidtb51** [comment]
@wurstbrot Thank you for your contribution. Due to the rules of OASIS, we might not be able to accept your suggestion via a Pull Request (even though we known it is often easier to create a PR than trying to describe where a file is). Knowing that you can't use the formal way via csaf-comment mailing list right now, we will discuss the issue.

I'll set the PR to draft for now. Due to the formal rules, a TC member might need to create the PR. Nevertheless, again: Thank you for your contribution.

**Comment by tschmidtb51** [comment]
@sthagen, @santosomar, @mprpic: I would suggest to add a disclaimer to the file instead.

**Comment by mprpic** [comment]
Red Hat no longer publishes CVRF files as of Sep of 2023, and the API endpoint this PR points to will also be removed at some point: https://access.redhat.com/articles/124913.

**Pull request closed without merging**
