### PR TITLE
PURL

### LINKED ISSUE #126: Create proposal to add purl, and swid properties to full_product_name_t
Given robust product identification is an important factor for consumers of Security Advisories (SAs) this proposal shall offer other optional properties to the Full Product Name type (`full_product_name_t`) side by side with Common Product Enumeration CPE (`cpe`).

The inputs are the Software Package Data Exchange® ([SPDX](https://spdx.github.io/spdx-spec/)®) and [CycloneDX](https://cyclonedx.org) specifications in their latest published versions.

## Rationale:
CPE is not the only way to identify products. In CycloneDX it is marked as deprecated. 
While the communities seem to split their focus, no one seems to really want to keep CPE.
* some to SWID - ISO-IEC 19770-2 Software Identification (SWID) Tags [spec is paywalled :-1:]
* others to PackageURL (purl - https://github.com/package-url/purl-spec) CycloneDX and SPDX support this already
  * https://spdx.github.io/spdx-spec/appendix-VI-external-repository-identifiers/#purl (ibid also interesting [cpe23](https://spdx.github.io/spdx-spec/appendix-VI-external-repository-identifiers/#cpe23type) regex pattern :wink:)
  * https://cyclonedx.org/docs/1.2/#type_component (XML)
  * https://cyclonedx.org/schema/bom-1.2.schema.json (JSON)
* ...

This is IMO a dangerous situation for CSAF, as we have not many stakes in the discussions. 

So, I suggest we support the main contenders. This way, the sharing communities of SAs have more options than tunneling data of other provenience say through a cpe field.

We had this unfortunate stuation of tunneling already in the past: In the wild producers placing CVSS3 as payload to CVSS2 fields ...

### PR DESCRIPTION
**Pull request by tschmidtb51**
- resolves #126 
- remove comment
- change regex
- adopt prose

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@pombredanne Please review that change concerning PURL representation in CSAF.

**Review by sthagen — APPROVED** [review]
LGTM a partial regex - we should reach out to
@pombredanne (Philippe Ombredanne), @ stevespringett (Steve Springett), or other members of the purl-spec community, if this structural constraint collides with the future plans for purl or if it looks ok.

**Comment by tschmidtb51** [comment]
@stevespringett, @pombredanne: Do you have any additional comments or can we proceed with that PR?

FYI: The PR provides a regex in addition to the URL check:
"^pkg:[A-Za-z\\.\\-\\+][A-Za-z0-9\\.\\-\\+]*/.+" 

I think that captures enough of the structure and ensures the canonical form of purl but leaves plenty of room to be future prove.

**Comment by stevespringett** [comment]
@tschmidtb51 Does the regex take into consideration percent encoded strings?

**Comment by tschmidtb51** [comment]
@stevespringett To be honest: No. But that is not necessary:

- `^pkg:` matches the **scheme**
- `[A-Za-z\\.\\-\\+][A-Za-z0-9\\.\\-\\+]*` matches the **type**. According to the [spec](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst#rules-for-each-purl-component):
   - The package type is composed only of ASCII letters and numbers, '.', '+' and '-' (period, plus, and dash)
   - The type cannot start with a number
   - The type cannot contains spaces
   - *The type must NOT be percent-encoded*
- `/.+` matches either the **name** or the **namespace**. According to the [spec](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst#rules-for-each-purl-component) each of them *must be a percent-encoded string*. But `/.+` just says that there must be any character after the `/`.

It certainly matches a things that are not valid PURLs (e.g. `pkg:maven/@1.3.4`) but it should give enough guidance to enforce valid URI/URL per [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3). For the rest, dedicated libraries SHOULD be used. That allows CSAF still to be valid if the PURL spec is updated (as long as the rules for **type** and the separator `/` do not change).

**Comment by tschmidtb51** [comment]
@santosomar, @sthagen We did not received feedback from @pombredanne (in #126) and @stevespringett. We replied to both without changes (as it was already covered by the suggested regex). We did not receive further feedback to this. Therefore, I suggest to merge it (to provide a full CSD for review) and point it out in the TC meeting.

@stevespringett, @pombredanne If you want to provide additional comments - please feel free to do so.

**Comment by stevespringett** [comment]
I think this approach is solid and future-proof. No further comments from me.

**Comment by santosomar** [comment]
> I think this approach is solid and future-proof. No further comments from me.

Thank you so much @stevespringett !

**Review by santosomar — APPROVED** [review]

**Pull request merged**
