### PR TITLE
Hashes

### PR DESCRIPTION
**Pull request by tschmidtb51**
- resolves comments from #208 and #209
- provide an array with hashes for each filename
- add remark about interpretation of filename mismatch at hash match
- change default value to `sha256`
- use digest list from OpenSSL

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@sthagen: Should we add an informational reference to OpenSSL?

@native_speakers: Is it `filename` or `file name`?

@all: Do you have a better suggestion for the `title` of items in the `hashes` array?

**Comment by tschmidtb51** [comment]
@santosomar: We should discuss these questions tonight.

**Comment by sthagen** [comment]
Yes @tschmidtb51 I think an informative reference to openssl is in order when we suggest the use of the nomenclature from that project / toolbox

**Comment by tschmidtb51** [comment]
> Yes @tschmidtb51 I think an informative reference to openssl is in order when we suggest the use of the nomenclature from that project / toolbox

Does that suit our purpose or should we refer to the project's GitHub repo?

**Review by sthagen — APPROVED** [review]
LGTM.

**Comment by sthagen** [comment]
> Does that suit our purpose or should we refer to the project's GitHub repo?

I think it does. Github is a brand in itself. So, if a project operates an own web presence I would always prefer that as to be explicit about the diversity and the contributions of individual natural persons technology really depends upon.

**Review by sthagen — APPROVED** [review]

**Comment by tschmidtb51** [comment]
It was decided during the TC meeting at 28.04.2021 to wait for comments for one week.

**Comment by santosomar** [comment]
There are some minor conflicts in the pull request. Please review https://github.com/oasis-tcs/csaf/pull/239/conflicts and I will merge right after.

**Comment by santosomar** [comment]
I have addressed the conflict and will merge shortly.

**Pull request merged**
