### PR TITLE
Seeding the Prose for the Spec

### PR DESCRIPTION
**Pull request by sthagen**
This is still work in progress but already with the automated github rendering offers quite readable prose for our spec draft.

* I suggest a dedication for Eric
  * there is prior art [where we lost a member in DSS-X TC](http://docs.oasis-open.org/dss-x/profiles/visualsig/v1.0/oasis-dssx-1.0-profiles-visualsig.html)
    * just to indicate my faith, that if the TC accepts such a dedication I do not expect formal discussions with TC administration
* All mandatory sections are formally there and in place
* Acknowledgments should include the prior version (already present)
* The rendering will include table of content when done like TC admins will do
* I am still cleaning up the tangle/weave 😺 helpers and hope we can decide to resolve some of my editorial issue w.r.t. the schema ordering and completeness of meta properties
  * This will ease the parsing for human readers and derivation of prose content by my tools

PS: Displaying the "[rich diff](https://github.com/oasis-tcs/csaf/pull/118/files?short_path=8dace39#diff-8dace39748f07bc75c173ded56c9a860)" renders the document a tad more WYSIWYG (besides the cutting lines between green addition bars) 😉

### CODE REVIEW

**Comment by sthagen** [comment]
@tolim, @tschmidtb51 here we go my initial markdown based draft. Hopefully we can optimize the json schema for human readers and our tools alike (as in the issues I opened over the last days):
* #106 
* #107 
* #108 
* #109 
* #110 
* #111 
* #112 
* #113 
* #114 
* #115

**Comment by sthagen** [comment]
@chet-ensign I added you as reviewer so you can easily follow the initial steps of using the markdown template - there is no obligation to spend time now (in that raw state of affairs) if you are busy. Any change requested from TC Administration of course will always be considered and if possible resolved with unanimous consent.

**Comment by dennypage** [comment]
Stefan, thank you for the Eric dedication. Deeply appreciated.

**Comment by santosomar** [comment]
Thank you very much for the contribution. As discussed in the TC meeting today (Sep 2, 2020), I am merging this pull request. Additional work and comments can be addressed in new GitHub issues and new pull requests.

**Comment by chet-ensign** [comment]
Thanks very much, Stefan.

**Pull request merged**
