### PR TITLE
Simplify test call per user set labels of paikalta

### PR DESCRIPTION
**Pull request by sthagen**
paikalta versions 2023.2.23 and up offer user defined labels (<https://codes.dilettant.life/docs/paikalta/changes/#2023223>). Using these simplifies the test driver.

### CODE REVIEW

**Comment by sthagen** [comment]
@tschmidtb51 I wonder if we are double checking here 😁 seeing (push) as well as (pull_request) actions both being triggered in a pull request ...

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Comment by tschmidtb51** [comment]
> @tschmidtb51 I wonder if we are double checking here grin seeing (push) as well as (pull_request) actions both being triggered in a pull request ...

I wonder about that as well - but I should consult the documentation first before I fully understand what the issue is...

**Review by sthagen — COMMENTED** [review]
Thanks.

**Pull request merged**
