### PR TITLE
Sharing groups

### PR DESCRIPTION
**Pull request by tschmidtb51**
- resolves https://github.com/oasis-tcs/csaf/issues/705
- add `sharing_group` to JSON schema
- adapt prose to reflect sharing group changes
- add RFC 9562 to normative references
- add RFC 4122 to informative references
- add mandatory test to prevent usage of Max UUID in other TLP than CLEAR (6.1.39)
- add mandatory test to prevent usage other UUID than Max UUID in TLP:CLEAR (6.1.40)
- add mandatory test to prevent usage of reserved names (6.1.41)
- add mandatory test to enforce usage of sharing group names (6.1.42)
- add rule about the relationship between sharing group ID and `/document/tracking/id`
- add optional test to discourage usage of Max UUID (6.2.28)
- add optional test to discourage usage of Nil UUID (6.2.29)
- add optional test to discourage usage sharing group with TLP:CLEAR (6.2.30)
- add invalid examples
- add valid examples
- adapt testcases list and schema
- add suggestions for quick fixes throughout the sharing group tests
- add guidance of size for UUIDs
- swap date and URI to make it alphabetic amongst the "special" strings
- convert headings into title case

### CODE REVIEW

**Review by sthagen — APPROVED** [review]
LGTM. Will need some editorial post work when the conflicts are resolved and the change set is merged into the editorial branch.

**Comment by tschmidtb51** [comment]
Pending motion: https://groups.oasis-open.org/discussion/motion-for-826

**Review by santosomar — APPROVED** [review]

**Comment by santosomar** [comment]
Dear CSAF TC Members,

The motion to accept the changes described in pull request as suggested in https://github.com/oasis-tcs/csaf/pull/826 and include it into CSAF 2.1 has passed.

**Review by santosomar — APPROVED** [review]

**Comment by tschmidtb51** [comment]
Merge branch `editor-revision-2024-11-27` into the sharing-groups.

**Pull request merged**
