### PR TITLE
Filled in section 1.1 to describe the changes

### PR DESCRIPTION
**Pull request by sthagen**
The title says it all

### CODE REVIEW

**Comment by tschmidtb51** [comment]
Related to #663

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
Please see my comments

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Comment by sthagen** [comment]
I prepared the following motion ready to be sent:

Dear members,

I hereby submit the following motion and request that if seconded and no objection received per this list before one week has passed on 2023-12-15T17:00:00Z to automatically carry. The Chair will of course subsequently state the result per mail to this list when the period has passed. The motion can be superseded by a TC meeting with quorum within the period mentioned above. 

Stefan Hagen moves that the TC approve Common Security Advisory Framework Version 2.0 Errata 01 and all associated artifacts packaged together in [csaf-2_0-errata-01-csd-01-20231208-rc1.zip](https://www.oasis-open.org/committees/document.php?document_id=71571&wg_abbrev=csaf) as an Errata Draft to Common Security Advisory Framework Version 2.0 OASIS Standard approved on 18 November 2022 and confirm that the errata corrections do not constitute Substantive Changes to the Standard.

Stefan Hagen further moves that the TC approve submitting Common Security Advisory Framework Version 2.0 Errata 01 contained in [csaf-2_0-errata-01-csd-01-20231208-rc1.zip](https://www.oasis-open.org/committees/document.php?document_id=71571&wg_abbrev=csaf) for 15 day public review.

# SHA256 Checksums

## Archive

fcce65c3905cd9685662f632313d608b5d345743db033241c52a56e71069bf48  csaf-2_0-errata-01-csd-01-20231208-rc1.zip
`

## Included Artifacts

6e76b27b9552168e756f4b1c8be0a9d43414338ee44793e55357869b86031242  aggregator_json_schema.json
29c114b35b0a30831f1674f2ab8b3ed9b2890cfeaa63b924ac6ed9d70ef44262  csaf_json_schema.json
716db1494b4843ae7ea7328122a1ff77387a728446b57c90950026581630e634  index.md
0270d0cfadf5202ff83a63502012a407e0e8ec3194a07296f13641c9f5630aba  provider_json_schema.json

**Pull request merged**
