### PR TITLE
SBOM

### PR DESCRIPTION
**Pull request by tschmidtb51**
- addresses parts of #126 
- add list of SBOM urls to `product_identification_helper` to have a dedicated place to link a product to its SBOM(s) (instead of using `x_generic_uris`)

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@sthagen: Can you please add the references to SBOM, SPDX, CycloneDX and SWID in the correct places?

**Comment by tschmidtb51** [comment]
@allan-ntia: Please check that we didn't miss anything here.

**Review by sthagen — APPROVED** [review]
That should be a good start. Discussions on adding informative text on the use of mime types to implementers of automations now has a place to start, no matter what additional info we end up with in addition (and where that goes).

Very well done, @tschmidtb51 ! Thanks.

**Comment by allan-ntia** [comment]
Looks reasonable to me, but we should give a pointer to the VEX working group so that they can make sure everything lines up.

**Comment by sthagen** [comment]
> @sthagen: Can you please add the references to SBOM, SPDX, CycloneDX and SWID in the correct places?

Sure. Will do.

**Review by mprpic — APPROVED** [review]
Nice! LGTM!

**Comment by santosomar** [comment]
This issue was discussed during the CSAF TC Monthly meeting on May 26th, 2021. The changes suggested were approved.

**Pull request merged**
