### PR TITLE
Editor revision for TC meeting 2024-03-27

### LINKED ISSUE #579: Write purl instead of PURL
The seems to prefer `purl` over PURL: https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst

### LINKED ISSUE #708: v2.0 OS failed CPSR-coding in section 9.1.13 Conformance Clause 13: CSAF asset matching system
In section 9.1.17 Conformance Clause 17: CSAF SBOM matching system of the CSAF v2.0 OS is a trace of failed CPSR-coding in list item 11 it says:

> - is able to trigger a run of the asset matching module:

which would be correct within section 9.1.13 Conformance Clause 13: CSAF asset matching system
but for the SBOM matching system it is expected that the run of an SBOM matching module is triggered instead:

> - is able to trigger a run of the SBOM matching module:

<https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#9117-conformance-clause-17-csaf-sbom-matching-system>

kudos to an anonymous spotter 👀

### PR DESCRIPTION
**Pull request by tschmidtb51**
- Editor revision for CSAF 2.1 (based on #699)
- addresses #693 
- fixes #710 
- fixes #708 
- fixes #579 
- addresses parts of #652

### CODE REVIEW

**Review by sthagen — APPROVED** [review]
LGTM.

**Comment by tschmidtb51** [comment]
As discussed in today's TC meeting: We will keep that open until 2024-04-10 for TC review. If no objections occur, it will be merged.

**Review by sthagen — APPROVED** [review]
```python
'LGTM'.lower()
```

**Comment by santosomar** [comment]
A motion will be moved after today's CSAF TC meeting. We agreed that no further changes are pending for this PR.

**Review by santosomar — APPROVED** [review]

**Comment by santosomar** [comment]
The motion to accept the Editor Revision 2024-03-27 as suggested in github.com/oasis-tcs/csaf/pulls/714 into our master branch has passed. https://groups.oasis-open.org/discussion/motion-for-714

**Pull request merged**
