### PR TITLE
Language type

### LINKED ISSUE #71: Language type regular expression
#67 was reviewed and approved by TC during the June 24, 2020 monthly meeting. @santosomar summarizes the discussions and call for suggestions about the pattern:

> TC members are encouraged to suggest any additional edits to the pattern/string "pattern": "^[a-zA-Z]{2,3}(-.+)?$" . Additional information about the convention (https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) and other items are documented in the associated issue and were also discussed during the June 24, 2020 monthly meeting.

This is an issue to track and discuss these suggestions.

### PR DESCRIPTION
**Pull request by tschmidtb51**
- resolves #71 
- corrects regex
- skips deprecated grandfathered
- change prose to match schema
- add remark about privateuse

### CODE REVIEW

**Review by sthagen — APPROVED** [review]
LGTM but, I cannot try the regex - does it work in the known cases?

**Review by sthagen — APPROVED** [review]

**Review by sthagen — APPROVED** [review]

**Comment by tschmidtb51** [comment]
@santosomar Please review.

**Review by sthagen — APPROVED** [review]

**Review by sthagen — APPROVED** [review]

**Comment by tschmidtb51** [comment]
I think this is now ready for merge.

**Comment by santosomar** [comment]
Looks like there are still some conflicts.

**Comment by tschmidtb51** [comment]
> Looks like there are still some conflicts.

Just resolved them.

**Pull request merged**
