### PR TITLE
Alternative to JSON Schema 2020-12 #294

### LINKED ISSUE #92: What jsonschema version to use
Given the fact, that draft 7 of jsonschema did expire in March 2020 we should analyze which version to settle on.

### PR DESCRIPTION
**Pull request by sthagen**
Technically I did not find a way to push to the existing JSON Schema 2020-12 #294 PR and thus created a branch on this repo with the changes from @tschmidtb51 `json-2020-12` branch and applied two minimally invasive fixes:

1. provide `git` to the Debian image
2. added the proposed install steps for the intermediate validator - thanks to @nezhar (Harald Nezbeda)

I propose to merge this PR instead of #294 - closes #92

### CODE REVIEW

**Review by tschmidtb51 — APPROVED** [review]
LGTM: Thanks for patching it.

**Comment by tschmidtb51** [comment]
Merge #297 first to include changes in prose.

**Review by sthagen — COMMENTED** [review]
LGTM.

**Review by santosomar — APPROVED** [review]
Thank you, both!

**Pull request merged**
