### PR TITLE
Redirects

### PR DESCRIPTION
**Pull request by tschmidtb51**
- resolves oasis-tcs/csaf#798
- add sentence about max redirects

### CODE REVIEW

**Review by sthagen — APPROVED** [review]
LGTM.

**Comment by sthagen** [comment]
Can sopmeone remind me of how we selected the numbers 5 and 10. Did we look at our hands ... 🙈 ?

**Comment by tschmidtb51** [comment]
Accidentally added editorial to it:
- fixes https://github.com/oasis-tcs/csaf/issues/811
- add comment that not redirects are allowed in requirement 9 and 10
- addresses parts of https://github.com/oasis-tcs/csaf/issues/318
- reflect current state of CSAF field in security.txt

@sthagen: Please review again.

**Review by sthagen — APPROVED** [review]
LGTM.

**Pull request merged**
