### PR TITLE
CPE Regex

### PR DESCRIPTION
**Pull request by tschmidtb51**
- addresses parts of #91
- take [regex](https://csrc.nist.gov/schema/cpe/2.2/cpe-language_2.2a.xsd) and [specification](https://cpe.mitre.org/files/cpe-specification_2.2.pdf) for CPE 2.2 from MITRE and adopt it
- fix the pattern to be valid JSON
- adopt prose to match schema

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@mprpic: Please have a look at it. It should add support for CPE 2.2.

**Review by sthagen — APPROVED** [review]
LGTM

**Comment by sthagen** [comment]
If @mprpic  this change is good for you too, I will merge.

**Comment by mprpic** [comment]
@sthagen Looks good, thank you!

**Review by mprpic — APPROVED** [review]

**Pull request merged**
