### PR TITLE
Distributing

### PR DESCRIPTION
**Pull request by tschmidtb51**
- addresses the first part of #152
- add rules agreed on TC meeting Jan 27th, 2021

### CODE REVIEW

**Review by sthagen — APPROVED** [review]
I think this is a good start. I wonder if other transports than per TLS might be desirable? What about QUIC?

**Comment by tschmidtb51** [comment]
> I think this is a good start. I wonder if other transports than per TLS might be desirable? What about QUIC?

AFAIK: QUIC incorporates TLS 1.3 (see [QUIC](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-delegation-to-quic).

**Comment by tschmidtb51** [comment]
@santosomar: Please review.

**Review by sthagen — APPROVED** [review]
:+1:

**Review by santosomar — APPROVED** [review]
Looks good! Thank you again for all your time and help!

**Pull request merged**
