### PR TITLE
Example consistency

### PR DESCRIPTION
**Pull request by tschmidtb51**
- fix inconsistency
- rename product_ids in example to match those which are used later in the document
- discovered with [Secvisogram](https://github.secvisogram.io)

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@mprpic: Please have a look at it since it changes the Red Hat example.

**Review by santosomar — APPROVED** [review]
Looks good from my side. I will wait until @mprpic approves it and will merge.

**Review by mprpic — APPROVED** [review]
LGTM! Thanks for the fix!

**Review by sthagen — COMMENTED** [review]
Thanks.

**Pull request merged**
