### PR TITLE
Suggestion for Definition of Product Status

### PR DESCRIPTION
**Pull request by tschmidtb51**
- resolves oasis-tcs/csaf#260
- add definitions to explain affected
- need decision on oasis-tcs/csaf#263

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@allan-ntia: Please review.

**Comment by allan-ntia** [comment]
I think this approach makes sense. 

I would just add this: I think some of the folks in the VEX world liked the set of examples of potential actions for known_affected. In particular, I've heard the idea that the consumer may have to learn more to take action. e.g. addressing vulns that are specific to configuration or other details, as well as the explicit acknowledgement that the action may be something other than a traditional patch. 

Now, we can always add the "for instance" text for the VEX profile. Just wanted to try to capture this feedback.

**Comment by tschmidtb51** [comment]
I tried to incorporate the feedback.

**Review by sthagen — APPROVED** [review]
I like it. Thanks.

**Comment by santosomar** [comment]
Same here! Thank you @tschmidtb51 @allan-ntia @sthagen!

**Review by santosomar — APPROVED** [review]

**Comment by tschmidtb51** [comment]
As discussed in VEX subgroup at Jun 7th, 2021: Okay. Ready to merge.

**Pull request merged**
