### PR TITLE
Search vs Filter

### PR DESCRIPTION
**Pull request by tschmidtb51**
- fixes oasis-tcs/csaf#730
- define filter and search

### CODE REVIEW

**Review by sthagen — APPROVED** [review]
LGTM.

**Review by santosomar — APPROVED** [review]
I agree with these suggested changes.

I also like the adjustments that were made to ensure proper validation of these new vector string properties.

These changes enhance the schema's flexibility for CVSS vector string representation.

**Review by justmurphy — APPROVED** [review]
LGTM

**Comment by santosomar** [comment]
A motion was moved by Omar to include the changes suggested in this pull request, during the CSAF TC monthly meeting on 2024-10-30. The motion was seconded by Thomas Schaffer. The motion passed.

**Pull request merged**
