### PR TITLE
Enumerate examples in prose

### PR DESCRIPTION
**Pull request by sthagen**
Enumerated all 104 examples (numbers 99 and 101 for ROLIE service and category doc are TODO.

This PR solves #304

PS: Updated log date, title date, and fixed a typo.

### CODE REVIEW

**Review by tschmidtb51 — COMMENTED** [review]
Thanks for adding these changes. 

As it is currently inconsistent, I have 2 questions:
1. Should the `:`inside or outside the `*[...]*`? E.g. `*Examples 42:*` or `*Examples 1*:`
2. How do we treat plural? Do we use "Examples" when we have multiple and "Example" when we have one?

**Comment by sthagen** [comment]
I did these 104 changes by hand, so I see no inconsistency but mistakes I made - I suggest the italic format to bracket the whole content so outside the colon - any asterisk preceding the colon is a typo. The singular plural is by choice. I see an enumeration as an isolated tag and do not need a constant prefix. So if there are examples than it would be `*Examples 42 ...` and if only a simple example then `*Example 42 ...` (I left all nouns as they were, so there may be a mismatch between the multiplicity of the example term and the actual number of examples present in the block.

**Comment by sthagen** [comment]
The amended PR should now be consistent within the flexibility we offer for the singular vs. plural depending on the content.

Note, that the source format markdown eases automatic extraction of the examples per start regex token `^\ *\*Example` & end token the second `^\ *```aaa` following a start token.

**Review by santosomar — APPROVED** [review]
I like the way you are allowing for these examples and completely agree to have the ability to include multiple (plural). Thank you all!!

**Pull request merged**
