### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by tschmidtb51**
- addresses part of oasis-tcs/csaf#195
- draft section structure

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@sthagen: Before I rewrite all the numbering: Is this the right place to out them in?

**Review by sthagen — APPROVED** [review]
LGTM - thanks.

**Review by sthagen — APPROVED** [review]

**Review by sthagen — APPROVED** [review]
Nice.

**Review by sthagen — APPROVED** [review]
LGTM

**Comment by tschmidtb51** [comment]
This addresses the first part of #195. 

@santosomar: Please add it to the agenda for the next TC meeting for voting.

**Comment by tschmidtb51** [comment]
For potential informational tests: see https://github.com/oasis-tcs/csaf/issues/195#issuecomment-827008177

**Comment by santosomar** [comment]
Will do, @tschmidtb51 ! Thank you!

**Review by sthagen — APPROVED** [review]

**Comment by tschmidtb51** [comment]
It was decided during the TC meeting at 28.04.2021 to wait for comments for one week.

**Comment by santosomar** [comment]
The comments will be done via the related issue  #195

**Pull request merged**
