### PR TITLE
Product numbers

### PR DESCRIPTION
**Pull request by tschmidtb51**
- addresses parts of #126
- add `product_numbers` (from the ordering process) to `product_identification_helper`

Reasoning: This information is usually available if you buy new equipment. [Wago](https://cert.vde.com/de-de/advisories/vde-2021-014), [Endress+Hauser](https://cert.vde.com/de-de/advisories/vde-2021-010), [PEPPERL+FUCHS](https://cert.vde.com/de-de/advisories/vde-2021-018), [Weidmüller](https://cert.vde.com/de-de/advisories/vde-2021-016),... already include them in their current advisories.

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@certvde, @tolim: Please review.

**Review by sthagen — APPROVED** [review]
LGTM - albeit someone might stumble over the product number being a string for us and in reality also …

**Comment by mprpic** [comment]
Is this not already covered by `serial_numbers`? Both objects are arrays of strings so I'm not sure what practical difference there is between _numbers_ and _serial numbers_.

**Comment by tschmidtb51** [comment]
A `serial_number` should be unique for each instance of a product. A `product_number` is unique for the product model.
 
For example:

I can tell from the Siemens `product_number` [6ES7212-1AF40-0XB0](https://www.siemens.com/tstcloud/?node=6ES7212-1AF40-0XB0) that this is a Siemens SIMATIC S7-1200F with CPU 1212FC in DC/DC/DC. I can order 100 pieces which will have the same `product_number` but different `serial_numbers`.

**Comment by sthagen** [comment]
We might call that better product_code?

**Comment by sthagen** [comment]
The discussion during the meeting suggests to maybe consider ski (stock keeping unit) instead?

**Comment by santosomar** [comment]
Definitions of SKUs shared during the CSAF TC Monthly meeting on May 26th, 2021.
https://www.britannica.com/technology/SKU
https://en.wikipedia.org/wiki/Stock_keeping_unit

This pull request will be merged in about 1 week from  May 26th, 2021.

**Review by santosomar — APPROVED** [review]
Looks good from my side. Thank you!

**Review by sthagen — APPROVED** [review]
Nice. Thanks.

**Comment by tschmidtb51** [comment]
I think that it ready for merge.

**Review by santosomar — APPROVED** [review]

**Pull request merged**
